"https://{default}/":
  type: upstream
  upstream: "web:http"

"https://{default}/inc/":
  type: upstream
  upstream: "api:http"
  cache:
    enabled: true
    default_ttl: 300

"https://api.{default}/":
  type: upstream
  upstream: "api:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"http://{default}/":
  type: redirect
  to: "https://{default}/"

"http://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://direct.joind.in/":
  type: upstream
  upstream: "web:http"

"https://direct.joind.in/inc/":
  type: upstream
  upstream: "api:http"
  cache:
    enabled: true
    default_ttl: 300

"https://api.direct.joind.in/":
  type: upstream
  id: "api"
  upstream: "api:http"

"https://www.direct.joind.in/":
  type: redirect
  to: "https://direct.joind.in/"

"http://direct.joind.in/":
  type: redirect
  to: "https://direct.joind.in/"

"http://www.direct.joind.in/":
  type: redirect
  to: "https://direct.joind.in/"