"https://{all}/":
  type: upstream
  upstream: "web:http"

"https://{all}/inc/":
  type: upstream
  upstream: "api:http"
  cache:
    enabled: true
    default_ttl: 300

"https://api.{all}/":
  type: upstream
  id: "api"
  upstream: "api:http"

"https://www.{all}/":
  type: redirect
  to: "https://{all}/"

"http://{all}/":
  type: redirect
  to: "https://{all}/"

"http://www.{all}/":
  type: redirect
  to: "https://{all}/"