"https://{default}/":
  type: upstream
  upstream: "web:http"

"http://api.{default}/":
  type: upstream
  id: "api"
  upstream: "api:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"http://{default}/":
  type: redirect
  to: "https://{default}/"

"http://www.{default}/":
  type: redirect
  to: "https://{default}/"