mysqldb:
  type: mysql:10.0
  disk: 256
  configuration:
    schemas:
      - joindin
    endpoints:
      admin:
        default_schema: joindin
        privileges:
          joindin: admin
      joindin:
        default_schema: joindin
        privileges:
          joindin: admin
