#If You change the the name of the mysgl service it will
#wipe the db make sure you have a good backup if that is your intent.
tmp:
  type: mysql:10.0
  disk: 256
  configuration:
    schemas:
      - joindin
    endpoints:
      admin:
        default_schema: joindin
        privileges:
          joindin: admin
      joindin:
        default_schema: joindin
        privileges:
          joindin: rw


redis:
  type: redis:5.0
