# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'api'

# The type key specifies the language and version for your application.
type: 'php:7.3'
size: M

# On PHP, there are multiple build flavors available. Pretty much everyone
# except Drupal 7 users will want the composer flavor.
build:
  flavor: none #Setting this to composer has no effect in submoduled repos.

variables:
  php:
      session.cookie_httponly: on
      session.cookie_secure: on

runtime:
  sizing_hints:
    request_memory: 10
  extensions:
    - newrelic

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  default: 'mysql:joindin'
  admin: 'mysql:admin'

# The hooks that will be triggered when the package is deployed.
hooks:
  # Build hooks can modify the application files on disk but not access any services like databases.
  build: |
    cp config_platformsh.php joindin-api/src/config.php
    cp database_platformsh.php joindin-api/src/database.php
    cd joindin-api
    composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
  #  rm web/app_dev.php
  # Deploy hooks can access services but the file system is now read-only.
  deploy: |
  #  app/console --env=prod cache:clear


# The size of the persistent disk of the application (in MB).
disk: 256

# The 'mounts' describe writable, persistent filesystem mounts in the application.
# The keys are directory paths relative to the application root. The values are a
# mount definition. In this case, `web-files` is just a unique name for the mount.
mounts:
  'joindin-api/tmp':
    source: local
    source_path: 'tmp'

# The configuration of the application when it is exposed to the web.
web:
  locations:
    "/":
      root: "joindin-api/public"
      passthru: "/index.php"
      #index:
      #  - index.php
      #scripts: true
      #allow: true
      #rules:
      #  '^(.*)$':
      #    passthru: '/index.php/$1'
    "/inc":
      root: "joindin-api/tmp"
      scripts: false
      rules:
        '\.(ico|flv|pdf|mov|mp3|wmv|ppt)$':
          allow: true
          expires: 300s
          headers:
            cache-control: "public"

        '\.(gif|jpg|jpeg|png|swf|txt|js|css)$':
          allow: true
          expires: 3600s
          headers:
            cache-control: "public"
